# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scene.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scene.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscene.proto\x12\x05scene\"\x07\n\x05\x45mpty\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"M\n\tRectangle\x12\x1d\n\x07topleft\x18\x01 \x01(\x0b\x32\x0c.scene.Point\x12!\n\x0b\x62ottomright\x18\x02 \x01(\x0b\x32\x0c.scene.Point\"\x8f\x01\n\x0bSceneConfig\x12\x1b\n\x05start\x18\x01 \x01(\x0b\x32\x0c.scene.Point\x12\x19\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x0c.scene.Point\x12#\n\tobstacles\x18\x03 \x03(\x0b\x32\x10.scene.Rectangle\x12#\n\tsafezones\x18\x04 \x03(\x0b\x32\x10.scene.Rectangle\"1\n\rSceneResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa7\x01\n\x0cSceneService\x12\x37\n\x0bUpdateScene\x12\x12.scene.SceneConfig\x1a\x14.scene.SceneResponse\x12,\n\x08GetScene\x12\x0c.scene.Empty\x1a\x12.scene.SceneConfig\x12\x30\n\nClearScene\x12\x0c.scene.Empty\x1a\x14.scene.SceneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scene_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_POINT']._serialized_start=31
  _globals['_POINT']._serialized_end=60
  _globals['_RECTANGLE']._serialized_start=62
  _globals['_RECTANGLE']._serialized_end=139
  _globals['_SCENECONFIG']._serialized_start=142
  _globals['_SCENECONFIG']._serialized_end=285
  _globals['_SCENERESPONSE']._serialized_start=287
  _globals['_SCENERESPONSE']._serialized_end=336
  _globals['_SCENESERVICE']._serialized_start=339
  _globals['_SCENESERVICE']._serialized_end=506
# @@protoc_insertion_point(module_scope)
