# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scene_pb2 as scene__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scene_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SceneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateScene = channel.unary_unary(
                '/scene.SceneService/UpdateScene',
                request_serializer=scene__pb2.SceneConfig.SerializeToString,
                response_deserializer=scene__pb2.SceneResponse.FromString,
                _registered_method=True)
        self.GetScene = channel.unary_unary(
                '/scene.SceneService/GetScene',
                request_serializer=scene__pb2.Empty.SerializeToString,
                response_deserializer=scene__pb2.SceneConfig.FromString,
                _registered_method=True)
        self.ClearScene = channel.unary_unary(
                '/scene.SceneService/ClearScene',
                request_serializer=scene__pb2.Empty.SerializeToString,
                response_deserializer=scene__pb2.SceneResponse.FromString,
                _registered_method=True)


class SceneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearScene(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SceneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateScene': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScene,
                    request_deserializer=scene__pb2.SceneConfig.FromString,
                    response_serializer=scene__pb2.SceneResponse.SerializeToString,
            ),
            'GetScene': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScene,
                    request_deserializer=scene__pb2.Empty.FromString,
                    response_serializer=scene__pb2.SceneConfig.SerializeToString,
            ),
            'ClearScene': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearScene,
                    request_deserializer=scene__pb2.Empty.FromString,
                    response_serializer=scene__pb2.SceneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scene.SceneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scene.SceneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SceneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scene.SceneService/UpdateScene',
            scene__pb2.SceneConfig.SerializeToString,
            scene__pb2.SceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scene.SceneService/GetScene',
            scene__pb2.Empty.SerializeToString,
            scene__pb2.SceneConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearScene(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scene.SceneService/ClearScene',
            scene__pb2.Empty.SerializeToString,
            scene__pb2.SceneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
